### ISSUE TITLE
qalhat

### ISSUE THREAD

**Issue by Hokath** [adaneslavo/More-Wonders-for-VP#10]
guess we need the icon for this, now

**Comment by adaneslavo** [comment]
Soon. I can slowly start work, but I need to code remaining ones :) Maybe add shadowing to previous icons.

**Comment by Hokath** [comment]
sure i can put the shadows on next
here is a mockup for this one 
![qalhat](https://user-images.githubusercontent.com/11889219/72567759-6ea51900-38ae-11ea-912c-712ee1edff05.png)

**Comment by adaneslavo** [comment]
For me colors are too messed up with background.

**Comment by Hokath** [comment]
yeah i dont like it either
![qalhat](https://user-images.githubusercontent.com/11889219/72568252-9f398280-38af-11ea-84b6-6b61c013eac5.png)

**Comment by adaneslavo** [comment]
Much better. Make the background more transparent and it will be probably done.

**Comment by Hokath** [comment]
by background do you mean the sunbeams or the dark clouds?

**Comment by adaneslavo** [comment]
Either make dark clouds brighter or sunbeams more transparent. When both are so intense they cannot be distinguished, especially when there are so many irregular forms on it.
