### ISSUE TITLE
Lavaux

### ISSUE THREAD

**Issue by Hokath** [adaneslavo/More-Wonders-for-VP#11]
guess we need an icon for this

**Comment by Hokath** [comment]
![Picture2](https://user-images.githubusercontent.com/11889219/72667176-bd6ac400-3a10-11ea-91d1-7450351fede8.png)

**Comment by Hokath** [comment]
![Picture2](https://user-images.githubusercontent.com/11889219/72667191-fd31ab80-3a10-11ea-8d39-ffb1a64c1221.png)

**Comment by adaneslavo** [comment]
Perfect!
