### ISSUE TITLE
wartburg

### ISSUE THREAD

**Issue by Hokath** [adaneslavo/More-Wonders-for-VP#12]
guess we need an icon for this

**Comment by Hokath** [comment]
![wartburg](https://user-images.githubusercontent.com/11889219/72671324-48af7e00-3a40-11ea-8c62-b87ebc9703eb.png)
thoughts

**Comment by adaneslavo** [comment]
Tower should fit the circle. Beside that ok.

**Comment by Hokath** [comment]
good point, done
