### ISSUE TITLE
Great Zimbabwe

### ISSUE THREAD

**Issue by adaneslavo** [adaneslavo/More-Wonders-for-VP#13]
New wonder coming...

**Comment by Hokath** [comment]
An icon exists in this civ mod
https://forums.civfanatics.com/threads/vox-populi-compatible-civilizations-showcase.574461/page-2#post-15270755

**Comment by adaneslavo** [comment]
I'm not sure we should borrow it. This mod is compatible with VP in MUCfVP so people can use it with our mod.

**Comment by Hokath** [comment]
your choice. 
I'm passing on making an icon for this

**Comment by adaneslavo** [comment]
You made it compatible with VP. Are you ok with that? If yes, I have no other concern.

**Comment by adaneslavo** [comment]
I found only such icon:
![obraz](https://user-images.githubusercontent.com/33016300/72861987-ca670c00-3ccb-11ea-9da9-02f34abbfb7b.png)
It is different than in the op. Am I missing something? If this is later version, then maybe we could use older here, with the green background.
![obraz](https://user-images.githubusercontent.com/33016300/72862023-f2566f80-3ccb-11ea-829b-d653c59a183d.png)

**Comment by Hokath** [comment]
The top one is the one with Lastswords mod.
The bottom looks like it is a remix from somewhere else, an error with the link on the picture perhaps.

I think its fine to use the top one, but personally I just wouldn't use this wonder given the overlap.

**Comment by Hokath** [comment]
the meenakshi temple would make dope icon
![image](https://user-images.githubusercontent.com/11889219/72982256-962c4200-3dd6-11ea-94e8-3b52400e46dd.png)

**Comment by adaneslavo** [comment]
For now I used this wonder, because of not so much African ones in the game and because I managed to create nice gold/expansion flavour for it. Also I don't want to delay 0.4 release even more. Today I made significant changes, maybe final so update is coming.

**Comment by Hokath** [comment]
Alright!
