### ISSUE TITLE
Falun Mine

### ISSUE THREAD

**Issue by adaneslavo** [adaneslavo/More-Wonders-for-VP#14]
New wonder added.

**Comment by Hokath** [comment]
![falun](https://user-images.githubusercontent.com/11889219/72685502-c2984380-3ae2-11ea-845e-a70a11c671fd.png)
found it really hard to find an image that looked any good.
even here it is hard to see the mine entrances, but it looks weird if i try to paint them bigger...

**Comment by adaneslavo** [comment]
Main goal is to keep Falu Red color on the picture.
https://en.wikipedia.org/wiki/Falu_red

**Comment by Hokath** [comment]
well that's the iron oxide all over the floor

**Comment by adaneslavo** [comment]
Ok, then. I thought it would be more reddish. Remember to upload Lavaux too if it is finished. I coded it today.

**Comment by adaneslavo** [comment]
Upload Falun Mine if you can.
