### ISSUE TITLE
Bamyan

### ISSUE THREAD

**Issue by Hokath** [adaneslavo/More-Wonders-for-VP#2]
to do soon

**Comment by Hokath** [comment]
![bamyancomp](https://user-images.githubusercontent.com/11889219/72217961-07ddd380-352d-11ea-9d3b-7da4400d56c5.png)
With or without sunbeams?

**Comment by adaneslavo** [comment]
Maybe sunbeams that omit sculpture?

**Comment by Hokath** [comment]
do you want to sketch what you mean? either side of the statue?

**Comment by adaneslavo** [comment]
Something like this:
![bamyan](https://user-images.githubusercontent.com/33016300/72219463-b17d8e80-3546-11ea-8b5a-2ac94e4f243d.png)

**Comment by adaneslavo** [comment]
In Gimp looks well. I will check in game later on.

**Comment by adaneslavo** [comment]
Looks good.
