### ISSUE TITLE
Natural Wonder Balance

### ISSUE THREAD

**Issue by Hokath** [adaneslavo/More-Wonders-for-VP#20]
I think you might need to bump the yields, I have two NW in my empire atm and I don't really want to work either of them over normal tiles.

**Comment by adaneslavo** [comment]
Which ones?

**Comment by Hokath** [comment]
I'll get you some quantitative comparisons next game

**Comment by adaneslavo** [comment]
Cool.

**Comment by adaneslavo** [comment]
Do you have any thoughts? I will try to make next update soon with new Wonder, maybe NW model's fix if Iamblichos will find the error, and it would be good to add some balance to this topic too.

**Comment by Hokath** [comment]
Not yet. I postponed playing another game because I was waiting for the airplane-disappear bug to be fixed. However it has taken a long time to get out a new version (still none as of today 2020/8/11)
