### ISSUE TITLE
Sanbo Honbu

### ISSUE THREAD

**Issue by Hokath** [adaneslavo/More-Wonders-for-VP#22]
What does this refer to? Best I can google is that it means the general staff of the japanese military, but I don't see how that is a world wonder?

**Comment by adaneslavo** [comment]
We were looking for military oriented "wonder" for authority branch. I open for suggestions if you have better one. It was suggested here:
https://forums.civfanatics.com/threads/more-wonders-for-vp.653498/page-6#post-15646645

**Comment by Hokath** [comment]
Ah ok so there is a pretty building  they lived in. Japanese pentagon :D Ok cool I can work with this.
