### ISSUE TITLE
Sanbo Honbu art

### ISSUE THREAD

**Issue by adaneslavo** [adaneslavo/More-Wonders-for-VP#23]
Sunbeams require small correction; they are not even if you look closer - one is very thin.

**Comment by Hokath** [comment]
better?

**Comment by adaneslavo** [comment]
Better, but still... one above flag is the widest. If you could make it and those on the right like those on the left it would be ideal :)

**Comment by Hokath** [comment]
I see it!

**Comment by adaneslavo** [comment]
After 3 years ;)

**Comment by Hokath** [comment]
I moved country and left the files behind. They have been uncovered in a recent Archaeological Dig.

**Comment by Hokath** [comment]
they were some really shit sunbeams tho :D
![Picture1](https://github.com/adaneslavo/More-Wonders-for-VP/assets/11889219/b83fcf8a-4a2a-4833-8b05-aa928aa939f5)

**Comment by Hokath** [comment]
[6.Modern.zip](https://github.com/adaneslavo/More-Wonders-for-VP/files/13802082/6.Modern.zip)
