### ISSUE TITLE
Hollywood art rework

### ISSUE THREAD

**Issue by adaneslavo** [adaneslavo/More-Wonders-for-VP#24]
Could you look at Hollywood icon? I don't like itat all; it was originally from previous mod. Can you make something with it?

**Comment by Hokath** [comment]
it can come over to the hokath style, yes

**Comment by Hokath** [comment]
pre-sunbeams, do you like any of these?
![image](https://github.com/adaneslavo/More-Wonders-for-VP/assets/11889219/ac0c1be2-5665-4f22-82f0-219cb3be98e2)

**Comment by adaneslavo** [comment]
Bottom left looks nice. If you cut one tree to make the sign a bit bigger it owuld be ideal.

**Comment by Hokath** [comment]
making the sign better was surprisingly painful, but through photoshop all things are possible.
![image](https://github.com/adaneslavo/More-Wonders-for-VP/assets/11889219/8366a3fa-7597-4fc7-b7dd-b020467f0072)

**Comment by Hokath** [comment]
[6.Modern2.zip](https://github.com/adaneslavo/More-Wonders-for-VP/files/13806576/6.Modern2.zip)

**Comment by adaneslavo** [comment]
Nice.
