### ISSUE TITLE
Golden Dagon Pagoda

### ISSUE THREAD

**Issue by Hokath** [adaneslavo/More-Wonders-for-VP#26]
Gives an Archaeologist long before I can dig

**Comment by adaneslavo** [comment]
So you are well prepared for digging :)
What do you suggest instead?

**Comment by Hokath** [comment]
A free GW, I guess?
    On Thursday, 20 August 2020, 18:25:26 BST, Adam <notifications@github.com> wrote:  
 
 


So you are well prepared for digging :)
What do you suggest instead?

**Comment by adaneslavo** [comment]
It is artifact related wonder, so archaeologist is helping to fill it later on. To directly create artifact I would need to resolve some old programming problem afair. And GW of art is not compatible with it.

Maybe later if I have time I will again try to make an artifact. Then Ark of the Covenant, Holy Crown of Hungary and Holy Spear could be changed to Artifacts as well.
