### ISSUE TITLE
Goebekli Tepe no Mountain Yields

### ISSUE THREAD

**Issue by Palaki** [adaneslavo/More-Wonders-for-VP#29]
Hello there! :) 
Currently playing as Germany with tons of mountains.
I was happy that i could build the wonder first, but sadly it seems the mountain yields arent working...
Are the yields meant to be added to the city, or to each tile? 
![Screenshot_1](https://user-images.githubusercontent.com/60859061/91374195-ea3d5000-e817-11ea-9344-54f864a9bf91.png)

Additionally i have to say that its often difficult/unclear for me to understand the new style of the wonders description texts. Just a small opinion. :)

Thank you for continuing the mod and sorry for my bad english.

**Comment by adaneslavo** [comment]
I will look on that. Maybe it is the same thing like with hills earlier...


DESCRIPRTIONS:
I try to make them as clear as possible. Adding much more generic text means that numeric info must be much more condensed than in vanilla. Can you make another post on github with some examples of what part of texts are unclear? Maybe I will think of reworking if it is necessary. Those text evolved many times, but now, I think they are not so bad.

Remember, you can always revert them to vanilla (info in the mod page), but I encourage you to do some analysis.

**Comment by adaneslavo** [comment]
BTW: those 2 mountains you where you placed citizen (those green with snow caps); those are **no mountains** at all. I guess you are playing v0.8.3, and in offical version models for NWs are not working yet. These 2 tiles are probably **Salar de Uyuni** considered flat desert tile.

**Comment by Palaki** [comment]
Yes im playing v08.3 and those 2 tiles are Salar de Uyuni. I already recognized that those tiles arent mountains in this version. But thats a minor issue, at least for me. My main concern is that shitload of Science and Faith i will not enjoy. :) The top left tile above the city is a mountain, so the city should at least get +1, +1, but it doesnt. Bought a second mountain tile just to test, didnt work either.

Regarding the texts... they arent bad! They add a nice flavor to the game. But i realized that i often opened the wonders wiki to search for more detailed information in my last playtrough. In vanilla VP this did not happen. Nice that there is an option to revert it to vanilla texts! Ill leave it flavored for now and check if i have problems in the future.

**Comment by Palaki** [comment]
Just found the Key for "Flavoured Help Texts" on modpage. I think with that some text will confuse me less...

**Comment by adaneslavo** [comment]
Good. I made it for new players, nad glad it helped you. Still, if you have some specific concerns about any descritpion, post it on forum or github, please.


I will check those mountains when I'm back home.

**Comment by adaneslavo** [comment]
As I thought bug was similar to old Hills bug. It is unbelievable that no one noticed that earlier!
