### ISSUE TITLE
chand baori

### ISSUE THREAD

**Issue by Hokath** [adaneslavo/More-Wonders-for-VP#3]
to do soon

**Comment by adaneslavo** [comment]
Not working. I pulled your icon but ingame it is only black spot.

**Comment by adaneslavo** [comment]
Remember to substitute files instead of pasting them into folder. Now there are 2 Majorville copies. I renamed files used for now to "Wonder_*" instead of old "VPWE*"

**Comment by Hokath** [comment]
I don't know why it would not load, I made them in exactly the same way.
Didn't see that you renamed them, sorry.

**Comment by adaneslavo** [comment]
It is wonderful! But You need to resize it slighlty:
![chand resize](https://user-images.githubusercontent.com/33016300/72218055-b20e2900-3536-11ea-9ff1-d08d51a06aaf.png)

**Comment by adaneslavo** [comment]
I cannot edit it because gimp says the file is "imported" and do not show me side bars with edit options.

**Comment by adaneslavo** [comment]
I updated files and folder structure. Be careful when uploading new stuff.

**Comment by Hokath** [comment]
I'll resize stuff once we work out the black dot thing.
I saved them with paint.net, can try gimp perhaps

**Comment by adaneslavo** [comment]
Better, but too much to south:
![chand-almost](https://user-images.githubusercontent.com/33016300/72220544-f6f38900-3551-11ea-8da5-adbe2951bf07.png)
![chand-almost2](https://user-images.githubusercontent.com/33016300/72220545-f6f38900-3551-11ea-801d-470b0aebd62b.png)

**Comment by Hokath** [comment]
It's no further south than the forge of damascus as far as my eyes can tell. gah.
oh well, i'll pull it up later

**Comment by adaneslavo** [comment]
I didn't look at forge yet. So maybe it will have to be moved too. Juest compare it with Etchmiadzin. It seems to be fit nicely.

**Comment by Hokath** [comment]
what size one is it, btw? the 256 one looks the same size as the etchmiadzin

**Comment by adaneslavo** [comment]
Civilopedia uses 256 probably.

**Comment by adaneslavo** [comment]
Now it's good. I  slighlty resized it and it is perect. I really like your art. But minor thing that you need to check by yourself: contrast of lines. Load the game and look on El ghriba or Etchiadzin, but lower res icon, not 256. I have strange feeling that contrast is too low or lines... I don't know. I am difficult and I hope you will not curse me :)

**Comment by adaneslavo** [comment]
Ahh, and shadows. All original and modded icons have shadow arc in left top part. I also tried to make such in my (look at Mohenjo-daro). You can add that to yours.

**Comment by Hokath** [comment]
aha yes the arc, I can do that.
i'll take a look at the smaller icons once you release 0.4 :D
