### ISSUE TITLE
Forum Romanum not buildable

### ISSUE THREAD

**Issue by Palaki** [adaneslavo/More-Wonders-for-VP#30]
Also v0.8.3.
Forum Romanum is not buildable, although requirements should be met. ( River, have 5 from 3 required politics)

This save is getting hard to enjoy slowly...

**Comment by adaneslavo** [comment]
Sorry for that. I have no time for such wide testing and all things you and other players find are very helpful. I will check that tomorrow.

You didn't mention Marsh. Do you have one in your city?

**Comment by Palaki** [comment]
Well, its still in development so people have to be prepared for some bugs. :)

My cities dont have marshes, but the tooltip is missing the marsh requirement either.
I have to say it also is missing its flavor description.

**Comment by adaneslavo** [comment]
That's interesting...

**Comment by adaneslavo** [comment]
In v0.8.3 it has no policy reduction in requirements, so only river and marsh is needed. I don't remember how was with the description in that version. In current github build everything seems fine, so probably was fixed.
![obraz](https://user-images.githubusercontent.com/33016300/91563205-c58fc800-e93e-11ea-9443-e78e8a97c58b.png)
