### ISSUE TITLE
Mount Everest graphic glitch

### ISSUE THREAD

**Issue by Palaki** [adaneslavo/More-Wonders-for-VP#31]
On new Github version Mount Everest looks a bit glitchy.

![Screenshot_1](https://user-images.githubusercontent.com/60859061/91512896-5638ba80-e8e3-11ea-9698-6e2bfa633d75.png)

**Comment by adaneslavo** [comment]
It's original model I copied from precursor mod. For now I have no ability to modify it, becuse it requires working 3D modelling tools which don't want to cooperate with me... For now it has to be in its current state like other models.
