### ISSUE TITLE
Emissaries Broken

### ISSUE THREAD

**Issue by Sage009** [adaneslavo/More-Wonders-for-VP#35]
Emissaries and Great Diplomats cannot pop themselves for influence in City States. I noticed the problem with the one you get from Scrivener's Office, then I tried buying one and the same problem occured.
Playing VP 3.2.2

**Comment by adaneslavo** [comment]
Are you sure that this mode caused the issue? Can you verify with VP 3.7 and MW v0.18?
If problem occurs, check only VP. I didn;t change Scrivener's Office in my mod.

**Comment by Sage009** [comment]
We stopped playing with the mod, as it also stopped units from promoting, so all units were stuck at level 1 permanently.
It was in hotseat multiplayer so I had to make the modpack myself. Including more wonders for vp in my modpack was most likely what caused these problems, as making the modpack without it has no issues, among any version from 3.2.2 to 3.4.4 (haven't tried any of the newer versions yet)

**Comment by adaneslavo** [comment]
Multiplayer issues will be fixed next version. We have just found the issue causing desyncs and probably more problems.
