### ISSUE TITLE
deep ocean research facility

### ISSUE THREAD

**Issue by Hokath** [adaneslavo/More-Wonders-for-VP#38]
is a bit early at Biology for this kind of name
plus the art is some futuristic shit :D

**Comment by adaneslavo** [comment]
I like the art. It's one of the best @gwennogs creations. And Biology seems the best tech for it. Biology is in Modern Era, and at that time there were first submarines built, right? Who cares they were only piece of junk? The idea matters ;P Use your imagination.

**Comment by Hokath** [comment]
Yes, I appreciate all that.
Perhaps swap name and art with the bathysphere building -- bathysphere is late 1920s maybe (still a bit late for biology, but certainly before this underwater research station idea)
