### ISSUE TITLE
etchmiadzin

### ISSUE THREAD

**Issue by Hokath** [adaneslavo/More-Wonders-for-VP#4]
to do soon

**Comment by Hokath** [comment]
I made this icon with gimp, try an open it and/or import it?

**Comment by adaneslavo** [comment]
This time works in game. You can lower the number of sunshines by 2 and make them same size and it will be perfect.

Unfortunately I still cannot edit them, but this is minor thing.

**Comment by Hokath** [comment]
ok so 4/4 sky regions, is that just because it is what the other wonders have or are the regions too small on the icon in-game?

**Comment by adaneslavo** [comment]
It has much more than other wonders. The most I could see was on St Basil, but still less.

**Comment by adaneslavo** [comment]
![obraz](https://user-images.githubusercontent.com/33016300/72220652-1ccd5d80-3553-11ea-8f17-30b0cc1917ae.png)
