### ISSUE TITLE
Plain of Jars

### ISSUE THREAD

**Issue by Hokath** [adaneslavo/More-Wonders-for-VP#40]
Having a fun early game with nice Mohenjo-Daro start.

It occurred to me that Plain of Jars might do better on Military Strategy. I got forward settled and had the time to build something before the war, might have been to do this but hadn't got Calendar yet.

Also Calendar has a wonder, Military Strategy has nothing.
For flavour, I believe the legend about this IRL is to do with a battle and so forth, so it can make sense.

p.s. You should mention on the tooltip how much faith you get!

**Comment by adaneslavo** [comment]
Tech will be changed.

I think I followed the standard texts from VP and that's why I haven't put the number for Marae and Plain of Jars in normal tooltips. I can add them though.
