### ISSUE TITLE
Yerba de la Fleche

### ISSUE THREAD

**Issue by Hokath** [adaneslavo/More-Wonders-for-VP#41]
I don't like how high variance this instakill promotion is, especially in the early game.

Perhaps +% to wounded units is more in keeping with other promotions?

**Comment by adaneslavo** [comment]
It's really rare (requires Tropical Fish, so only available when GBR or Galapagos is on), and used only by Archery units, not available late game. Do you think it is overpowered? It's only 5% chance. I can lower it even more. Or I can do as you suggest giving let's say +50% dmg to wounded units?

**Comment by Hokath** [comment]
I think the problem is the variance. Lowering the chance doesn't really solve the problem (it actually makes it weirder if it ever does happen!).

I think a promo like +% dmg is the way to go.

In other news, I think the idea of adding more sources of tropical fish somehow is also a good one.

**Comment by adaneslavo** [comment]
Reworked for the testing.
