### ISSUE TITLE
St. Peter's

### ISSUE THREAD

**Issue by Hokath** [adaneslavo/More-Wonders-for-VP#43]
The entry ExtraLeagueVotes doesn't do exactly what it sounds like.
As a result, having this wonder gives extra votes equal to the number of city states at the start of the game (!)

For reference, on Palace of Westminster this entry is set to for 4 (so start with 24, you get 6 votes).

**Comment by Hokath** [comment]
Also look into Old Bridge in Mostar

**Comment by adaneslavo** [comment]
I remember checking that and I left these with scaling on purpose. So with 1 we get 24? That is stupid...

**Comment by adaneslavo** [comment]
Ok. I will fix it. The only issue is St. Peter's Basilica.
