### ISSUE TITLE
Mohenjo-daro

### ISSUE THREAD

**Issue by adaneslavo** [adaneslavo/More-Wonders-for-VP#6]
I'm not happy with my art. Could be refined.

**Comment by Hokath** [comment]
I like it personally!

**Comment by adaneslavo** [comment]
Yeah but it goes outside the circle and the art is a bit fuzzy... It's not totally worthless, but with your skill it can be upgraded.

**Comment by Hokath** [comment]
Ill try get this done at the weekend.

In the mean time check out this ceiling
![20200130_200424](https://user-images.githubusercontent.com/11889219/73486045-33214900-439c-11ea-842d-09dc5bb92316.jpg)
Sun beams everywhere

**Comment by adaneslavo** [comment]
Nice. Do all made-by-you icons have shadows? I cannot remember. We started talking about that in mid work. Also, what do you thing about "sharpness" (contrast?) of the icons compared to original ones? Its some time before I take up for renaissance, so you can easily do some "finishing".

**Comment by adaneslavo** [comment]
@Hokath Are you still with me before we start renaissance? I still think that Mohenjo icon should be reworked. We need to get rid of my temporary one... :)

**Comment by adaneslavo** [comment]
![obraz](https://user-images.githubusercontent.com/33016300/74614877-04390000-511c-11ea-8cd6-f41ddce77bfe.png)
I like overall work and colour palette, but don't you think it should depict city itself not the ruins?
