### ISSUE TITLE
Wieliczka

### ISSUE THREAD

**Issue by adaneslavo** [adaneslavo/More-Wonders-for-VP#7]
Current icon is ugly and nothing can be seen on it.

**Comment by Hokath** [comment]
yeah its gross, will take a look
I like how we can have a wonder that makes salt OP again :D

**Comment by adaneslavo** [comment]
:) If you have other idea regarding resource requirements or buffsm or improvements feel free to share. I have restricted imagination. Personally Wieliczka looks the most original from what we've added for now.

**Comment by Hokath** [comment]
![saltmine](https://user-images.githubusercontent.com/11889219/72387774-379efe00-371c-11ea-8be8-0514f30d7e2d.png)
thoughts? is the shadowy arc too strong?

**Comment by adaneslavo** [comment]
Could be slightly thinner and more transparent, but beside that looks awesome :)

**Comment by adaneslavo** [comment]
Now it's ideal.
